### ISSUE TITLE
Virtual Server 1 not using configured port

### ISSUE THREAD

**Issue by h4ppywastaken** [TeamSpeak-Systems/ts-services#18]
# Describe the bug
When I change the ports in the docker-compose.yaml file from 9987 to 9988, the virtual server will still bind to 9987.

## Steps to reproduce:
docker-compose.yaml
teamspeak:
    expose:
      - "9988:9988/udp"
      - "10012/tcp" # RAW, Telnet
      - "10023/tcp" # SSH, 'secure' Telnet
    ports:
      - "9988:9988/udp"
      - "10023:10023/tcp" # SSH, 'secure' Telnet
      - "10012:10012/tcp" # RAW, Telnet

docker compose --profile setup pull
docker compose run --rm setup --domain=*** --email=***
docker compose up -d

docker container logs ts-services-teamspeak-1 -f
2023-02-21 15:53:05.046260|INFO    |VirtualServerBase|1  |listening on 0.0.0.0:9987, [::]:9987

# Used versions/hash
ts-services beta-58rc18 / teamspeak_server beta14-rc11

**Comment by Gamer92000** [comment]
This is expected behavior. You did not change the port the TS server listens to, just the forwarding within docker.
You can more or less ignore how the ports are managed within each docker container. The only thing you need to worry about is what they are mapped to on the host.
So what you want to do is:
```yaml
- "9988:9997/udp" # <port on host>:<port in container>/protocol
```

This way the log will still say it's listening on port `9987` but it will be accessible through port `9988` on the host.
I don't see a way to currently change the port of the binary in the container itself.

**Comment by h4ppywastaken** [comment]
Thank you very much - this clarified how the port configuration works!
